spring:
    profiles.active: dev
    application:
        name: order-system
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5Dialect
            naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/order-system?useSSL=false
        username: root
        password:
        testWhileIdle: true
        validationQuery: SELECT 1

kafkaConsumer:
  bootstrapServers: xx.xx.xx.xx:9092 # update this url
  groupId: ORDER_SYSTEM_GROUP_ID

kafkaTopics:
  smsTopic: SMS_TOPIC
  emailTopic: EMAIL_TOPIC
  invoiceTopic: INVOICE_TOPIC


pdfLocation: /Users/gouravsoni/Desktop/

email:
  from: gourav@gmail.com # update this
  password: userPassword # update this
  smtpHost: smtp.gmail.com
  smtpPort: 587
  body: this is order confirmation email.
  fileNotFoundMsg: Invoice will be sent shortly.